const {initializeApp} = require("firebase-admin/app");
initializeApp();
// const {siteFunction, siteWarsaw} = require("./sites/rzk.com.ru");
// const {botFunction} = require("./bot");
const {productsUploadFunction} = require("./bot/bot_upload_scene");
const {siteWarsawSecondGen} = require("./sites/rzk.com.ru/index-gcf-2nd");
const {botFunctionSecondGen} = require("./bot/index-gcf-v2");
// exports.site = siteFunction;
// exports.siteWarsaw = siteWarsaw;
// exports.bot = botFunction;
exports.siteWarsawSecondGen = siteWarsawSecondGen;
exports.botFunctionSecondGen = botFunctionSecondGen;
exports.productsUpload = productsUploadFunction;
exports.triggers = require("./triggers");
